### ISSUE TITLE
NOT ABLE TO STREAM MOVIES ONLINE !!

### ISSUE THREAD

**Issue by JeelTikiwala** [namansukhwani/Flextream#6]
Your efforts are quite good but there is some internal server error and the movie is not playing on browser. 
![Screenshot 2021-08-17 222127](https://user-images.githubusercontent.com/69708737/129767920-8458c69e-41ef-4048-852a-aa641046c462.jpg)

**Comment by namansukhwani** [comment]
@JeelTikiwala 
Yes I know that, actually for streaming it requires to connect to the webRTC peers available. But currently all the webRTC peers are dead for the torrents. So this issue is related to the torrent peers. UDP peers are available to connect but as it is an web app it uses HTTPS and UDP is an unencrypted protocol so browsers don't allow that. I have a desktop app version of the app that runs on electron and allows the UDP connection also, but it isn't completed right now. I will complete it once I will get the time.
Thanks for checking out the app.
